# Generated by Django 5.2 on 2026-06-27 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('company', models.CharField(blank=True, max_length=120)),
                ('source', models.CharField(choices=[('referral', 'Referral'), ('website', 'Website'), ('whatsapp', 'WhatsApp'), ('email', 'Email Campaign'), ('social', 'Social Media'), ('ads', 'Paid Ads'), ('event', 'Event'), ('cold_call', 'Cold Call'), ('other', 'Other')], default='website', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('converted', 'Converted'), ('lost', 'Lost')], default='new', max_length=20)),
                ('assigned_to', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('lead_score', models.IntegerField(default=0)),
                ('score_reason', models.TextField(blank=True)),
                ('conversion_probability', models.CharField(blank=True, max_length=20)),
                ('score_computed_at', models.DateTimeField(blank=True, null=True)),
                ('follow_up_suggestion', models.TextField(blank=True)),
                ('follow_up_generated_at', models.DateTimeField(blank=True, null=True)),
                ('last_contacted', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('created', 'Lead Created'), ('contacted', 'Contacted'), ('email_sent', 'Email Sent'), ('whatsapp_sent', 'WhatsApp Sent'), ('call', 'Call Made'), ('meeting', 'Meeting Scheduled'), ('note', 'Note Added'), ('status_change', 'Status Changed'), ('converted', 'Converted'), ('lost', 'Lost')], max_length=30)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_activities', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='leads.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['owner', 'status'], name='leads_lead_owner_i_9c310b_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['owner', 'source'], name='leads_lead_owner_i_d305b2_idx'),
        ),
    ]
