# Generated by Django 5.2.15 on 2026-06-12 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email'), ('rcs', 'RCS')], max_length=20)),
                ('recipient', models.CharField(max_length=150)),
                ('personalized_message', models.TextField()),
                ('current_status', models.CharField(choices=[('created', 'Created'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('opened', 'Opened'), ('read', 'Read'), ('clicked', 'Clicked'), ('converted', 'Converted')], default='created', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='campaigns.campaign')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('opened', 'Opened'), ('read', 'Read'), ('clicked', 'Clicked'), ('converted', 'Converted')], max_length=20)),
                ('channel', models.CharField(max_length=20)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='communications.communication')),
            ],
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['campaign'], name='communicati_campaig_9f2eaa_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['customer'], name='communicati_custome_a0ba9b_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['current_status'], name='communicati_current_b4d9b6_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationevent',
            index=models.Index(fields=['communication'], name='communicati_communi_7f785b_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationevent',
            index=models.Index(fields=['event_type'], name='communicati_event_t_ff29bb_idx'),
        ),
        migrations.AddConstraint(
            model_name='communicationevent',
            constraint=models.UniqueConstraint(fields=('communication', 'event_type'), name='unique_communication_event_type'),
        ),
    ]
