# Generated by Django 5.2.15 on 2026-06-12 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('segment', 'Segment'), ('message', 'Message'), ('channel', 'Channel'), ('insight', 'Insight'), ('planner', 'Planner')], max_length=30)),
                ('input_prompt', models.TextField()),
                ('output_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_recommendations', to='campaigns.campaign')),
            ],
        ),
    ]
