# Generated by Django 5.2.15 on 2026-06-12 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('segments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('goal', models.TextField()),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email'), ('rcs', 'RCS')], max_length=20)),
                ('message_template', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('launching', 'Launching'), ('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('target_audience_count', models.PositiveIntegerField(default=0)),
                ('ai_reasoning', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('launched_at', models.DateTimeField(blank=True, null=True)),
                ('dispatch_started_at', models.DateTimeField(blank=True, null=True)),
                ('dispatch_completed_at', models.DateTimeField(blank=True, null=True)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='segments.segment')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='campaigns_c_status_96cb56_idx'), models.Index(fields=['segment'], name='campaigns_c_segment_b350af_idx')],
            },
        ),
    ]
